version: "3.8"

services:
  ludus-optimizer:
    image: temperance.ludus-optimizer:latest
    container_name: ludus-optimizer
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HistoricalDatabase: "Server=host.docker.internal;Database=Historical;User ID=your_user;Password=your_password;Encrypt=False;TrustServerCertificate=True;"
    restart: unless-stopped