version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - temperance_network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ludus-optimizer:
    build: .
    image: temperance.ludus-optimizer:latest
    container_name: ludus-optimizer
    networks:
      - temperance_network
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HistoricalDatabase: 'Server=host.docker.internal,1433;Database=Historical;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;'
      ConnectionStrings__DefaultConnection: 'Server=host.docker.internal,1433;Database=TradingBotDb;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;'
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "user"
      RabbitMQ__Password: "password"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  temperance_network:
    external: true