version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - temperance_network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ludus-optimizer:
    build: .
    image: temperance.ludus-optimizer:latest
    container_name: ludus-optimizer
    networks:
      - temperance_network
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_ENVIRONMENT: "Development"
      ConnectionStrings__HistoricalDatabase: 'Server=host.docker.internal,1433;Database=Historical;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;'
      ConnectionStrings__DefaultConnection: 'Server=host.docker.internal,1433;Database=TradingBotDb;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;'
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "user"
      RabbitMQ__Password: "password"
      
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      CUDA_CACHE_DISABLE: "0"
      TF_FORCE_GPU_ALLOW_GROWTH: "true"
      TF_CPP_MIN_LOG_LEVEL: "1"
      
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Temperance.Ludus: "Debug"
    
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    runtime: nvidia
    
    # Additional GPU-related configurations
    shm_size: '2gb'  # Increased shared memory for GPU operations
    
    volumes:
      - cuda_cache:/app/.nv/ComputeCache

networks:
  temperance_network:
    external: true

volumes:
  cuda_cache:
    driver: local