version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - temperance_network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ludus-optimizer:
    image: temperance-ludus:latest
    container_name: ludus-optimizer
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - temperance_network
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ConductorApi__BaseUrl=http://conductor-api:8002 

      - ConnectionStrings__HistoricalDatabase=Server=host.docker.internal,1433;Database=Historical;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=TradingBotDb;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password
      - PythonSettings__SharedDataPath=/app/models 
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  cuda_cache:
    driver: local

networks:
  temperance_network:
    external: true